name: Build Firmware (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make

      - name: Show toolchain version
        run: arm-none-eabi-gcc --version

      - name: Build (same as local)
        run: |
          chmod +x build.sh || true
          ./build.sh

      - name: List artifacts
        run: ls -la firmware.* || true

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            firmware.bin
            firmware.hex
            firmware.elf
            firmware.map
          if-no-files-found: error
