name: Build Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install ARM toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi
    
    - name: Build firmware
      run: |
        echo "Building for NUCLEO-C071RB..."
        
        # Compile
        arm-none-eabi-gcc -c -mcpu=cortex-m0plus -mthumb -O2 -g main.c -o main.o
        arm-none-eabi-gcc -c -mcpu=cortex-m0plus -mthumb -O2 -g startup.c -o startup.o
        
        # Link
        arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb \
          -T STM32C071RBTx.ld \
          -nostdlib \
          -Wl,--gc-sections \
          -Wl,-Map=firmware.map \
          main.o startup.o \
          -o firmware.elf
        
        # Create binary
        arm-none-eabi-objcopy -O binary firmware.elf firmware.bin
        arm-none-eabi-objcopy -O ihex firmware.elf firmware.hex
        
        # Show size
        arm-none-eabi-size firmware.elf
    
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          firmware.bin
          firmware.hex
          firmware.elf
          firmware.map
